[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyDMS-sorption"
version = "0.9.0"
description = "Python package for physics-informed dual-mode sorption (DMS) optimization"
readme = "README.rst"
requires-python = ">=3.9"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
  { name = "Brandon C. Tapia"},
  { name = "Pablo A. Dean" },
  { name = "Jing Ying Yeo" },
  { name = "Albert X. Wu" },
  { name = "Zachary P. Smith", email = "smithlab_software@mit.edu" }
]

dependencies = [
  "numpy",
  "matplotlib",
  "Pillow",
  "reportlab",
  "scipy",
  "statsmodels",
  "scikit-learn"]

keywords = ["sorption", "membranes", "gas separation", "polymer modeling"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Physics"]


[project.optional-dependencies]
dev = ["pytest", "black", "build", "twine"]
docs = ["sphinx", "sphinxcontrib-bibtex", "sphinx_copybutton", "furo"]
publish = ["build", "twine"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"pyDMS.images" = ["*.png"]

[tool.setuptools.packages.find]
where = ["."
]
include = ["pyDMS*"]

[tool.black]
target-version = ["py312"]
line-length = 100
skip-magic-trailing-comma = true
exclude = '''
/(
    examples
)/
'''
